title: Einführung in empirische und experimentelle Forschungsmethoden
logo: http://www.presse.uni-wuerzburg.de/fileadmin/uniwue/ci/Logos/Pixelgrafiken/web/unilogo4cohne.png
description: Wintersemester 2019
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
